;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Event.Montage.Kick",DevComment="")
+GameplayTagList=(Tag="Gameplay.Ability.Combat.Punch",DevComment="")
+GameplayTagList=(Tag="Gameplay.Ability.Movement.Dash",DevComment="")
+GameplayTagList=(Tag="Gameplay.Ability.Movement.Jump",DevComment="")
+GameplayTagList=(Tag="Gameplay.Cooldown.Dash",DevComment="")
+GameplayTagList=(Tag="Gameplay.State.IsDashing",DevComment="")
+GameplayTagList=(Tag="Gameplay.State.IsJumping",DevComment="")
+GameplayTagList=(Tag="Gameplay.State.IsPunching",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Punch",DevComment="")

